name: CI Build & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      # Python və uv mühiti
      - name: Setup uv (+ Python 3.13)
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: true

      # Ruff linter
      - name: Ruff check
        run: uvx ruff check --output-format=github .

      # Docker build & up
      - name: Build & deploy Docker containers
        run: |
          sudo docker-compose down
          sudo docker-compose build --no-cache
          sudo docker-compose up -d
